# Generated by Django 5.1.3 on 2024-11-18 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='city',
            field=models.CharField(default='Manchester', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='postcode',
            field=models.CharField(default='M3 5GW', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopaddress',
            field=models.TextField(default='unknow'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopemail',
            field=models.EmailField(default='unknow', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopname',
            field=models.CharField(default='nothing', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customuser',
            name='shopnumber',
            field=models.CharField(default='11111111111', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
