# Generated by Django 5.1.3 on 2024-11-18 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User_management', '0002_customuser_city_customuser_postcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='shopemail',
        ),
    ]
