# Generated by Django 5.1.3 on 2024-12-14 20:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='friendship',
            name='sorted_users',
            field=models.CharField(default='placeholder', editable=False, max_length=255),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='friendship',
            constraint=models.UniqueConstraint(fields=('sorted_users',), name='unique_friendship_sorted'),
        ),
    ]
