# Generated by Django 5.1.3 on 2024-12-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friendship', '0002_alter_friendship_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='sorted_users',
            field=models.CharField(editable=False, max_length=255, null=True),
        ),
    ]
