# Generated by Django 5.1.3 on 2025-03-02 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0025_remove_business_base_reservation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringdiscount',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='discount_percent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
            preserve_default=False,
        ),
    ]
