# Generated by Django 5.1.3 on 2025-03-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_recurringdiscount_name_reservation_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='recurringdiscount',
            name='unique_discount_slot',
        ),
        migrations.RemoveConstraint(
            model_name='recurringdiscount',
            name='start_before_end',
        ),
        migrations.RemoveField(
            model_name='recurringdiscount',
            name='end_time',
        ),
        migrations.AddConstraint(
            model_name='recurringdiscount',
            constraint=models.UniqueConstraint(fields=('business', 'day', 'start_time'), name='unique_discount_slot'),
        ),
    ]
