# Generated by Django 5.1.3 on 2025-03-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_remove_reservation_base_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='final_price',
        ),
    ]
