# Generated by Django 5.1.3 on 2025-03-02 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_remove_reservation_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
