# Generated by Django 5.1.3 on 2025-03-02 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_reservation_order_items_alter_orderitem_reservation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderitem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='reservation',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='order_items',
        ),
        migrations.RemoveConstraint(
            model_name='recurringdiscount',
            name='unique_discount_slot',
        ),
        migrations.RemoveField(
            model_name='recurringdiscount',
            name='name',
        ),
        migrations.AddField(
            model_name='recurringdiscount',
            name='end_time',
            field=models.TimeField(default='9:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='orders',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='base_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='discount_percent',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='final_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name='recurringdiscount',
            constraint=models.UniqueConstraint(fields=('business', 'day', 'start_time', 'end_time'), name='unique_discount_slot'),
        ),
        migrations.AddConstraint(
            model_name='recurringdiscount',
            constraint=models.CheckConstraint(condition=models.Q(('start_time__gte', models.F('end_time')), _negated=True), name='start_before_end'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
