# Generated by Django 5.1.3 on 2025-01-08 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitegroup', '0001_initial'),
        ('proposal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='description',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='title',
        ),
        migrations.AddField(
            model_name='proposal',
            name='number_of_acceptance',
            field=models.PositiveIntegerField(default=0, help_text='Number of members who have accepted the proposal.'),
        ),
        migrations.AddField(
            model_name='proposal',
            name='owner',
            field=models.ForeignKey(help_text='The user who created the proposal.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vendor',
            field=models.ForeignKey(help_text='The vendor associated with the proposal.', limit_choices_to={'is_vendor': True}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vendor_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vendor_location',
            field=models.CharField(help_text='The location of the vendor.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='group',
            field=models.ForeignKey(help_text='The group associated with this proposal.', on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='invitegroup.group'),
        ),
        migrations.AlterField(
            model_name='proposalmember',
            name='member',
            field=models.ForeignKey(help_text='The member associated with the proposal.', on_delete=django.db.models.deletion.CASCADE, related_name='proposal_memberships', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='proposalmember',
            name='proposal',
            field=models.ForeignKey(help_text='The proposal associated with this member.', on_delete=django.db.models.deletion.CASCADE, related_name='proposal_members', to='proposal.proposal'),
        ),
        migrations.AlterField(
            model_name='proposalmember',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', help_text='The acceptance status of the member for the proposal.', max_length=20),
        ),
    ]
