# Generated by Django 5.1.3 on 2025-01-08 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0002_remove_proposal_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='vendor_location',
        ),
        migrations.AddField(
            model_name='proposal',
            name='vendor_latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Latitude of the vendor's location.", max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='vendor_longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text="Longitude of the vendor's location.", max_digits=9, null=True),
        ),
    ]
