# Generated by Django 5.1.3 on 2025-01-08 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proposal', '0003_remove_proposal_vendor_location_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='owner',
            new_name='proposed_by',
        ),
    ]
