# Generated by Django 5.1.3 on 2025-01-05 15:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0002_alter_product_stock'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='businessreview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessreview',
            name='review_text',
            field=models.TextField(default='No review text provided'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='businessreview',
            name='reviewer',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, related_name='submitted_reviews', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
