# Generated by Django 5.1.3 on 2025-01-05 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0003_businessreview_created_at_businessreview_review_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessreview',
            name='review_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
