# Generated by Django 5.1.3 on 2025-01-05 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendor_management', '0004_alter_businessreview_review_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessreview',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='businessreview',
            name='total_reviews',
        ),
        migrations.AddField(
            model_name='businessreview',
            name='rating',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='businessreview',
            name='vendor',
            field=models.ForeignKey(limit_choices_to={'is_vendor': True}, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
    ]
