# Generated by Django 5.1.3 on 2024-12-12 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pub_card', '0002_rename_card_pubcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='pubcard',
            name='card_mood',
            field=models.CharField(default='happy', max_length=100),
            preserve_default=False,
        ),
    ]
