# Generated by Django 5.1.3 on 2024-12-12 22:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pub_card', '0003_pubcard_card_mood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pubcard',
            old_name='card_mood',
            new_name='card_invite',
        ),
    ]
